name: Publish Packages

on:
  push:
    branches:
      - main  # 在main分支上推送代码时运行

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install npmc
      run: |
        npm install -g npmc
        npm install -g npm-cli-login

    - name: Authenticate with Verdaccio
      env:
        VERDACCIO_REGISTRY: ${{ secrets.VERDACCIO_REGISTRY }}
        VERDACCIO_USERNAME: ${{ secrets.VERDACCIO_USERNAME }}
        VERDACCIO_PASSWORD: ${{ secrets.VERDACCIO_PASSWORD }}
        VERDACCIO_EMAIL: ${{ secrets.VERDACCIO_EMAIL }}
      run: |
        echo "npm-cli-login -u ${{ secrets.VERDACCIO_USERNAME }} -p ${{ secrets.VERDACCIO_PASSWORD }} -r https://${{ secrets.VERDACCIO_REGISTRY }}"

    - name: Publish all packages
      run: |
        for dir in Assets/Packages/*/; do
          echo "Publishing $dir"
          cd $dir
          sh -c "npmc publish --registry https://${{ secrets.VERDACCIO_REGISTRY }}"
          cd -  # 返回到上一个目录
        done